# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/coffeechain.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &Cooperative
        Name: CooperativeMSP
        ID: CooperativeMSP
        MSPDir: crypto-config/peerOrganizations/cooperative.coffeechain.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('CooperativeMSP.admin', 'CooperativeMSP.peer', 'CooperativeMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('CooperativeMSP.admin', 'CooperativeMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('CooperativeMSP.admin')"

    - &Transporter
        Name: TransporterMSP
        ID: TransporterMSP
        MSPDir: crypto-config/peerOrganizations/transporter.coffeechain.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('TransporterMSP.admin', 'TransporterMSP.peer', 'TransporterMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('TransporterMSP.admin', 'TransporterMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('TransporterMSP.admin')"
                
    - &Miller
        Name: MillerMSP
        ID: MillerMSP
        MSPDir: crypto-config/peerOrganizations/miller.coffeechain.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('MillerMSP.admin', 'MillerMSP.peer', 'MillerMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('MillerMSP.admin', 'MillerMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('MillerMSP.admin')"
                
    - &Insurance
        Name: InsuranceMSP
        ID: InsuranceMSP
        MSPDir: crypto-config/peerOrganizations/insurance.coffeechain.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('InsuranceMSP.admin', 'InsuranceMSP.peer', 'InsuranceMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('InsuranceMSP.admin', 'InsuranceMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('InsuranceMSP.admin')"

Capabilities:
    Channel: &ChannelCapabilities
        V1_4_3: true
        V1_3: false
        V1_1: false
    Orderer: &OrdererCapabilities
        V1_4_2: true
        V1_1: false
    Application: &ApplicationCapabilities
        V1_4_2: true
        V1_3: false
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.coffeechain.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    SupplyOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Cooperative
                    - *Transporter
                    - *Miller
                    - *Insurance
    SupplyChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Cooperative
                - *Transporter
                - *Miller
                - *Insurance
            Capabilities:
                <<: *ApplicationCapabilities

