OrdererOrgs:
  - Name: Orderer
    Domain: coffeechain.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Cooperative
    Domain: cooperative.coffeechain.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Transporter
    Domain: transporter.coffeechain.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Miller
    Domain: miller.coffeechain.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Insurance
    Domain: insurance.coffeechain.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1