# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.coffeechain.com:
    container_name: orderer.coffeechain.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/coffeechain.com/orderers/orderer.coffeechain.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/coffeechain.com/orderers/orderer.coffeechain.com/tls/:/var/hyperledger/orderer/tls
        - orderer.coffeechain.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.cooperative.coffeechain.com:
    container_name: peer0.cooperative.coffeechain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.cooperative.coffeechain.com
      - CORE_PEER_ADDRESS=peer0.cooperative.coffeechain.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.cooperative.coffeechain.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.transporter.coffeechain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.cooperative.coffeechain.com:7051
      - CORE_PEER_LOCALMSPID=CooperativeMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/cooperative.coffeechain.com/peers/peer0.cooperative.coffeechain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/cooperative.coffeechain.com/peers/peer0.cooperative.coffeechain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.cooperative.coffeechain.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.transporter.coffeechain.com:
    container_name: peer0.transporter.coffeechain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.transporter.coffeechain.com
      - CORE_PEER_ADDRESS=peer0.transporter.coffeechain.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.transporter.coffeechain.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.transporter.coffeechain.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.cooperative.coffeechain.com:9051
      - CORE_PEER_LOCALMSPID=TransporterMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/transporter.coffeechain.com/peers/peer0.transporter.coffeechain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/transporter.coffeechain.com/peers/peer0.transporter.coffeechain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.transporter.coffeechain.com:/var/hyperledger/production
    ports:
      - 9051:9051
      
  peer0.miller.coffeechain.com:
    container_name: peer0.miller.coffeechain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.miller.coffeechain.com
      - CORE_PEER_ADDRESS=peer0.miller.coffeechain.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.miller.coffeechain.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.miller.coffeechain.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.cooperative.coffeechain.com:10051
      - CORE_PEER_LOCALMSPID=MillerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/miller.coffeechain.com/peers/peer0.miller.coffeechain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/miller.coffeechain.com/peers/peer0.miller.coffeechain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.miller.coffeechain.com:/var/hyperledger/production
    ports:
      - 10051:10051
      
      
  peer0.insurance.coffeechain.com:
    container_name: peer0.insurance.coffeechain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.insurance.coffeechain.com
      - CORE_PEER_ADDRESS=peer0.insurance.coffeechain.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.insurance.coffeechain.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.insurance.coffeechain.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.cooperative.coffeechain.com:11051
      - CORE_PEER_LOCALMSPID=InsuranceMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/insurance.coffeechain.com/peers/peer0.insurance.coffeechain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/insurance.coffeechain.com/peers/peer0.insurance.coffeechain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.insurance.coffeechain.com:/var/hyperledger/production
    ports:
      - 11051:11051
      
  caCooperative:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-cooperative
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.cooperative.coffeechain.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/07a3b76c115b26d53b64649720af0ce54e463f4d3e4f499f124b849893582ef3_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.cooperative.coffeechain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/07a3b76c115b26d53b64649720af0ce54e463f4d3e4f499f124b849893582ef3_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/cooperative.coffeechain.com/ca/:/etc/hyperledger/fabric-ca-server-config
      
  caTransporter:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-transporter
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.transporter.coffeechain.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/7909c3649db627cbc57ae954259446e8af88b899ddef4cf898df4a408422c0cf_sk
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.transporter.coffeechain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/7909c3649db627cbc57ae954259446e8af88b899ddef4cf898df4a408422c0cf_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/transporter.coffeechain.com/ca/:/etc/hyperledger/fabric-ca-server-config
      
  caMiller:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-miller
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.miller.coffeechain.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/34b4ac2b6c67f324b9ec49d49414b9e7dfc74982eab4c81f780ba4e3a9202a03_sk
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.miller.coffeechain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/34b4ac2b6c67f324b9ec49d49414b9e7dfc74982eab4c81f780ba4e3a9202a03_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/miller.coffeechain.com/ca/:/etc/hyperledger/fabric-ca-server-config
      
      
  caInsurance:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-insurance
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.insurance.coffeechain.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/36c356c7317eca178edc5a650f728507871f4dddf7cb061dd8c2c60fb41579a9_sk
      - FABRIC_CA_SERVER_PORT=10054
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.insurance.coffeechain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/36c356c7317eca178edc5a650f728507871f4dddf7cb061dd8c2c60fb41579a9_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/insurance.coffeechain.com/ca/:/etc/hyperledger/fabric-ca-server-config
