# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.coffeechain.com:
    container_name: orderer.coffeechain.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/coffeechain.com/orderers/orderer.coffeechain.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/coffeechain.com/orderers/orderer.coffeechain.com/tls/:/var/hyperledger/orderer/tls
        - orderer.coffeechain.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.cooperative.coffeechain.com:
    container_name: peer0.cooperative.coffeechain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.cooperative.coffeechain.com
      - CORE_PEER_ADDRESS=peer0.cooperative.coffeechain.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.cooperative.coffeechain.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.transporter.coffeechain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.cooperative.coffeechain.com:7051
      - CORE_PEER_LOCALMSPID=CooperativeMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/cooperative.coffeechain.com/peers/peer0.cooperative.coffeechain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/cooperative.coffeechain.com/peers/peer0.cooperative.coffeechain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.cooperative.coffeechain.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.transporter.coffeechain.com:
    container_name: peer0.transporter.coffeechain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.transporter.coffeechain.com
      - CORE_PEER_ADDRESS=peer0.transporter.coffeechain.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.transporter.coffeechain.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.transporter.coffeechain.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.cooperative.coffeechain.com:9051
      - CORE_PEER_LOCALMSPID=TransporterMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/transporter.coffeechain.com/peers/peer0.transporter.coffeechain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/transporter.coffeechain.com/peers/peer0.transporter.coffeechain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.transporter.coffeechain.com:/var/hyperledger/production
    ports:
      - 9051:9051
      
  peer0.miller.coffeechain.com:
    container_name: peer0.miller.coffeechain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.miller.coffeechain.com
      - CORE_PEER_ADDRESS=peer0.miller.coffeechain.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.miller.coffeechain.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.miller.coffeechain.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.cooperative.coffeechain.com:10051
      - CORE_PEER_LOCALMSPID=MillerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/miller.coffeechain.com/peers/peer0.miller.coffeechain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/miller.coffeechain.com/peers/peer0.miller.coffeechain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.miller.coffeechain.com:/var/hyperledger/production
    ports:
      - 10051:10051
      
      
  peer0.insurance.coffeechain.com:
    container_name: peer0.insurance.coffeechain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.insurance.coffeechain.com
      - CORE_PEER_ADDRESS=peer0.insurance.coffeechain.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.insurance.coffeechain.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.insurance.coffeechain.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.cooperative.coffeechain.com:11051
      - CORE_PEER_LOCALMSPID=InsuranceMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/insurance.coffeechain.com/peers/peer0.insurance.coffeechain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/insurance.coffeechain.com/peers/peer0.insurance.coffeechain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.insurance.coffeechain.com:/var/hyperledger/production
    ports:
      - 11051:11051
      
  caCooperative:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-cooperative
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.cooperative.coffeechain.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/08720f934fc05ff6266b4ec201697d9ac75d94c3b707a5002cc4312b7825b6f6_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.cooperative.coffeechain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/08720f934fc05ff6266b4ec201697d9ac75d94c3b707a5002cc4312b7825b6f6_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/cooperative.coffeechain.com/ca/:/etc/hyperledger/fabric-ca-server-config
      
  caTransporter:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-transporter
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.transporter.coffeechain.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/2c6837036c09cef80c144d2be716383529990b26c9d67b976715c33f52b11eca_sk
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.transporter.coffeechain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/2c6837036c09cef80c144d2be716383529990b26c9d67b976715c33f52b11eca_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/transporter.coffeechain.com/ca/:/etc/hyperledger/fabric-ca-server-config
      
  caMiller:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-miller
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.miller.coffeechain.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/9d978125af70862c6d163a31312dd82f0d656129364e76505180b25990c4468a_sk
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.miller.coffeechain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/9d978125af70862c6d163a31312dd82f0d656129364e76505180b25990c4468a_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/miller.coffeechain.com/ca/:/etc/hyperledger/fabric-ca-server-config
      
      
  caInsurance:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-insurance
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.insurance.coffeechain.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/0bf9ddc4d4da36c99145a2a3ec0ba85e88293fd5f8285da25264b270975f16f0_sk
      - FABRIC_CA_SERVER_PORT=10054
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.insurance.coffeechain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/0bf9ddc4d4da36c99145a2a3ec0ba85e88293fd5f8285da25264b270975f16f0_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/insurance.coffeechain.com/ca/:/etc/hyperledger/fabric-ca-server-config
